name: Connect to Azure VM
description: Connects to an Azure virtual machine and runs specified commands

inputs:
  ip:
    description: 'IP address of the Azure VM'
    required: true
  key:
    description: 'SSH private key to authenticate with the Azure VM'
    required: true
    
runs:
  using: "composite"
  steps:

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Extract branch name
      shell: bash
      run: echo ${{ inputs.key }}
      id: extract_branch

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      env:
        STAGE: ${{ steps.extract_branch.outputs.branch }}
      with:
        host: ${{ inputs.ip }}
        key: ${{ inputs.key }}
        username: ingsis
        password: password
        envs: STAGE
        script: |
            cd infra
            ./compose.sh $STAGE
